# Generated by Django 3.2.19 on 2023-05-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
